### ISSUE TITLE
Status is always pending

### ISSUE THREAD

**Issue by DPr00f** [technomancy-dev/00#18]
Despite emails being sent, the status seen in the app is always marked as `Pending`

Did I miss anything during the configuration?

<img width="903" alt="image" src="https://github.com/technomancy-dev/00/assets/989959/8c5594d3-ac4d-4329-afbc-0dfbe828ab6c">

**Comment by liltechnomancer** [comment]
Interesting, what do you see in the logs tab? Also did you setup the AWS portion via SST or manually?

**Comment by DPr00f** [comment]
On the logs tab I see `200`. No errors on the `queue:send`.

I've set up the email and domain manually before running sst. Which threw an error and I removed the email and rerun sst.

I can run sst on another region and try again to see if that was related.

**Comment by liltechnomancer** [comment]
What was the region? You could be experiencing this same issue which I will hopefully have fixed shortly https://github.com/technomancy-dev/00/issues/16

**Comment by DPr00f** [comment]
Region is us-east-2. I'll try us-east-1 later on.

**Comment by liltechnomancer** [comment]
I think its the same issue then, should be resolved in an hour or so, testing now.

**Comment by liltechnomancer** [comment]
Issue should be resolved here is the PR https://github.com/technomancy-dev/00/pull/19

Could you make sure you are no longer experiencing this? Thanks!

**Comment by DPr00f** [comment]
Oh yeah it worked. Everything changed to delivered now.

Updating the container asked to create a user again btw. But you must already be aware of that. Thank you for the quick reply on thisz

**Comment by liltechnomancer** [comment]
> Updating the container asked to create a user again btw. 

This means you are not using a persistent volume, and the database is stored in container. I need to add docs around this but it varies by host so I haven't yet. Are you hosting the container on AWS?

**Comment by DPr00f** [comment]
It should be persistent. Running on kubernetes and the volume is on a NAS. But I rushed doing the setup need to double check

**Comment by liltechnomancer** [comment]
Interesting, if it looks good when you double check please make an issue for that as it should be fine if persisted.

**Comment by liltechnomancer** [comment]
In the mean time I will close this one, thanks for filing it!
