### ISSUE TITLE
Email delivered, but status is PENDING

### ISSUE THREAD

**Issue by jpainam** [technomancy-dev/00#25]
In /messages
![image](https://github.com/user-attachments/assets/a6bc9cc8-6d4e-4416-be83-b29fa4449dfd)

in /logs
<img width="733" alt="Screenshot 2024-07-26 at 9 34 22 PM" src="https://github.com/user-attachments/assets/05a9b9e0-ccea-4bc7-8159-96f67bcfe1f3">

In /emails
![image](https://github.com/user-attachments/assets/d215d2a4-d6d3-40b4-91dc-1f3c57c3917d)

**Comment by liltechnomancer** [comment]
Hey @jpainam we resolved this in discord correct?

**Comment by jpainam** [comment]
> Hey @jpainam we resolved this in discord correct?

Yes, we did. thanks. 

For future ref.

The `SQS` queue wasn't setup. I needed. to run `SST` setup first. This applies to those using docker as well.
